version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(github-actions-deps)"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(terraform-deps)"
    labels:
      - "dependencies"
      - "terraform"