name: Build IBM Image

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build IBM Image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4