name: Build Hetzner Image

permissions:
  contents: 'read'
  id-token: 'write'

on:
  workflow_call:
  workflow_dispatch:

env:
  HCP_CLI_VERSION: "0.8.0"
  PACKER_VERSION: "1.12.0"

jobs:
  build:
    name: Build Hetzner Image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure HCP Credentials
        uses: hashicorp/hcp-auth-action@v0.1.0
        with:
          workload_identity_provider: ${{ secrets.HCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Install HCP CLI
        uses: hashicorp/hcp-setup-action@v0.1.0
        with:
          version: ${{ env.HCP_CLI_VERSION }}

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Build Image
        working-directory: ./packer/hetzner/templates
        run: |
          # Define colors for logging
          GREEN='\033[38;5;82m'   # Bright green
          ORANGE='\033[38;5;208m' # Bright orange
          RED='\033[38;5;196m'    # Bright red
          RESET='\033[0m'         # Reset to default color

          log_success() { printf "${GREEN}[SUCCESS] %s${RESET}\n\n" "$1"; }
          log_warning() { printf "${ORANGE}[WARNING] %s${RESET}\n" "$1"; }
          log_error() { printf "${RED}[ERROR] %s${RESET}\n" "$1"; }
          log_info() { printf "[INFO] %s\n" "$1"; }

          # Configure Hetzner credentials
          log_info "Configuring Hetzner credentials..."
          export HCLOUD_TOKEN="${{ secrets.HCLOUD_TOKEN }}" || {
            log_error "Failed to configure Hetzner credentials!"
            exit 1
          }
          log_success "Hetzner credentials configured successfully."

          # Run Packer
          log_info "Initializing Packer build..."
          packer init ./hetzner.pkr.hcl || {
            log_error "Failed to initialize Packer build!"
            exit 1
          }
          log_success "Packer build initialized successfully."

          log_info "Starting Packer build..."
          packer build ./hetzner.pkr.hcl || {
            log_error "Failed to build Hetzner image!"
            exit 1
          }
          log_success "Hetzner image built successfully."
          