name: Packer Validate Syntax (Multicloud)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  security-events: write

env:
  PACKER_VERSION: "latest"

jobs:
  packer-validate:
    name: Run Packer Validate for Multi-Cloud Templates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Run Packer Validate for Multi-Cloud Templates
        run: |
          # Initialize SARIF file
          echo '{"runs": [{"tool": {"driver": {"name": "Packer Validate", "informationUri": "https://developer.hashicorp.com/packer/docs/commands/validate"}},"results": [' > packer-results.sarif
          
          # Find all Packer template files (*.pkr.hcl) while excluding certain directories
          find . \
            -type d \( -path "./.github/workflows" -o -path "./.git" \) -prune -o \
            -name "*.pkr.hcl" -print | while read -r file; do

              # Echo which root folder is being processed
              echo "Processing file: $file..."

              # Get the directory of the file
              template_dir=$(dirname "$file")

              # Initialize Packer plugins in the directory
              packer init "$template_dir"

              # Run syntax-only validation
              validation_output=$(packer validate -syntax-only "$file" 2>&1)
              validation_status=$?

              # If validation fails, log the error message in SARIF format
              if [ $validation_status -ne 0 ]; then
                escaped_output=$(echo "$validation_output" | jq -R -s '.')
                echo "{\"message\": {\"text\": $escaped_output}}," >> packer-results.sarif
              fi
          done

          # Close SARIF JSON structure properly
          echo "{}]}]}' >> packer-results.sarif

          # Fix trailing comma issue in the SARIF file
          sed -i '$ s/},$/}]/' packer-results.sarif
  

      - name: Upload Packer Validate results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: packer-results.sarif
