name: Repository CVE Scan

permissions:
  security-events: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trivy-scan:
    name: Trivy Scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy scan in filesystem mode
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: 'fs'
          scanners: 'vuln,secret,misconfig,license'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy.sarif'

  gitleaks-scan:
    name: GitLeaks Scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run GitLeaks scan on repository
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_NOTIFY_USER_LIST: '@Timotej979'
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
