name: Reviewdog Code Review

on:
  pull_request:
    branches: [main, stage, dev]
  push:
    branches: [main, stage, dev]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  typo-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Typo Check (PR Review)
        uses: reviewdog/action-typos@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          typos_flags: '--config .github/workflows/typos-config/typos.toml'
          reporter: github-pr-review
          filter_mode: diff_context

      - name: Typo Check (Checks Tab)
        uses: reviewdog/action-typos@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          typos_flags: '--config .github/workflows/typos-config/typos.toml'
          reporter: github-check
          filter_mode: nofilter

  markdownlint-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Markdown Lint (PR Review)
        uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context
          markdownlint_flags: '. --config .github/workflows/markdownlint-config/markdownlint.txt'

      - name: Markdown Lint (Checks Tab)
        uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter
          markdownlint_flags: '. --config .github/workflows/markdownlint-config/markdownlint.txt' 

  gitleaks-scan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Gitleaks Scan (PR Review)
        uses: reviewdog/action-gitleaks@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context

      - name: Gitleaks Scan (Checks Tab)
        uses: reviewdog/action-gitleaks@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter

  detect-secrets-scan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Detect Secrets (PR Review)
        uses: reviewdog/action-detect-secrets@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context

      - name: Detect Secrets (Checks Tab)
        uses: reviewdog/action-detect-secrets@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter

  github_actions_lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: GitHub Actions Lint (PR Review)
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context

      - name: GitHub Actions Lint (Checks Tab)
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter

  shfmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: shfmt (PR Review)
        uses: reviewdog/action-shfmt@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          shfmt_flags: "-i 4 -ci"
          filter_mode: diff_context

      - name: shfmt (Checks Tab)
        uses: reviewdog/action-shfmt@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          shfmt_flags: "-i 4 -ci"
          filter_mode: nofilter

  shellcheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: ShellCheck (PR Review)
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context

      - name: ShellCheck (Checks Tab)
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter

  tflint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: TFLint (PR Review)
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tflint_rulesets: "aws azurerm google"
          reporter: github-pr-review
          filter_mode: diff_context

      - name: TFLint (Checks Tab)
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tflint_rulesets: "aws azurerm google"
          reporter: github-check
          filter_mode: nofilter

  terraform-validate:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        provider: [aws, azure, gcp]
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Validate ${{ matrix.provider }} (PR Review)
        uses: reviewdog/action-terraform-validate@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          terraform_version: 1.12.0
          workdir: terraform/${{ matrix.provider }}
          reporter: github-pr-review
          filter_mode: diff_context

      - name: Terraform Validate ${{ matrix.provider }} (Checks Tab)
        uses: reviewdog/action-terraform-validate@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          terraform_version: 1.12.0
          workdir: terraform/${{ matrix.provider }}
          reporter: github-check
          filter_mode: nofilter

  tfsec-scan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: tfsec Scan (PR Review)
        uses: reviewdog/action-tfsec@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context

      - name: tfsec Scan (Checks Tab)
        uses: reviewdog/action-tfsec@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter
