name: Reviewdog Commit Check

on:
  push:
    branches: [main, stage, dev]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  typo-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Typos
        uses: reviewdog/action-typos@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          typos_flags: '--config .github/workflows/typos-config/typos.toml'
          reporter: github-check
          filter_mode: nofilter

  markdownlint-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Markdownlint
        uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          markdownlint_flags: '. --config .github/workflows/markdownlint-config/markdownlint.txt'
          reporter: github-check
          filter_mode: nofilter

  gitleaks-scan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Gitleaks Scan
        uses: reviewdog/action-gitleaks@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter

  detect-secrets-scan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Detect Secrets Scan
        uses: reviewdog/action-detect-secrets@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          detect_secrets_flags: '--exclude-files .git/*'
          reporter: github-check
          filter_mode: nofilter

  github_actions_lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: GitHub Actions Lint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter

  shfmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Shfmt
        uses: reviewdog/action-shfmt@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          shfmt_flags: "-i 4 -ci"
          filter_mode: nofilter

  shellcheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: ShellCheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter

  tflint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: TFLint
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tflint_rulesets: "aws azurerm google"
          reporter: github-check
          filter_mode: nofilter

  terraform-validate:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        provider: [aws, azure, gcp, hcp, alicloud, tencent]
    steps:
      - uses: actions/checkout@v5

      - name: Terraform Validate
        uses: reviewdog/action-terraform-validate@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          terraform_version: 1.12.0
          workdir: terraform/${{ matrix.provider }}
          reporter: github-check
          filter_mode: nofilter

  tfsec-scan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: TFSec Scan
        uses: reviewdog/action-tfsec@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter
