name: ShellCheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  shellcheck:
    name: Run ShellCheck for install TalosOS scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find and Lint Shell Scripts
        run: |
          find . -type d \( -path "./.github/workflows" -o -path "./.git" \) -prune -o \
          -path "*/scripts/install-talos.sh" -exec shellcheck {} +
