name: Install TalosOS Script ShellCheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  security-events: write

jobs:
  shellcheck:
    name: Run ShellCheck for install TalosOS scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ShellCheck with SARIF output
        uses: reactive-firewall/shellcheck-scan@v1
        with:
          path: "**/scripts/install-talos.sh"
