name: ShellCheck Scan

permissions:
  security-events: write
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  shellcheck:
    name: ShellCheck Scan
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        shell: [bash, sh, dash, ksh]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ShellCheck with SARIF output
        uses: reactive-firewall/shellcheck-scan@v1.1
        with:
          shell-format: ${{ matrix.shell }}
          publish-artifacts: no