name: Install TalosOS Script ShellCheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  security-events: write
  contents: read

jobs:
  shellcheck:
    name: Run ShellCheck for install TalosOS scripts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell: [bash, sh, dash, ksh]  # Test scripts with multiple shells

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ShellCheck with SARIF output
        uses: reactive-firewall/shellcheck-scan@v1.1
        with:
          shell-format: ${{ matrix.shell }}
          publish-artifacts: no